language: elixir

elixir:
  - 1.7.1

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix format --check-formatted
  - mix credo --strict
  - mix test
